language: php

php: [5.3, 5.4, 5.5, 5.6, hhvm-nightly]

sudo: false

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - composer selfupdate
  - composer install --prefer-source

script:
  - php tests/concurrent_tests.php
  - bin/php-cs-fixer fix --verbose . --level=symfony
